macos_arm64_task:
  env:
    # Build configuration
    BUILD_TYPE: "Release"
    QT_VERSION: "6.3.1"
    QT_ARCH: "clang_64"
  container:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:latest
    cpu: 8
  install_dependencies_script:
    - brew install python cmake
    - python3 -m pip install aqtinstall
  install_qt_script:
    - python3 -m aqt install-qt mac desktop "$QT_VERSION" "$QT_ARCH" -O "$HOME/Qt"
  build_script:
    - cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=/usr -DUSE_TESTS=ON
    - make -j8
  test_script:
    - $CIRRUS_WORKING_DIR/lib/test/spotify-qt-lib-test
  package_script:
    macdeployqt build/spotify-qt.app -dmg -verbose=2
  artifacts:
    path: "build/spotify-qt.dmg"